/* ###
 * IP: GHIDRA
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ghidra.framework.plugintool;

/**
 * A {@link Plugin} that can save and restore transient state
 * <p>
 * Plugins should implements this if they have state that needs to be saved as domain objects get
 * switched between active and inactive, i.e., when the user tabs to a different domain object and
 * back. Whatever object is returned by {@link #getTransientState()} state will be fed back to this
 * plugin via {@link #restoreTransientState(Object)} after the tool state is switched back to the
 * domain object that was active.
 * 
 * @param <T> the type used to record the state, usually a Java {@code record}
 */
public interface PluginWithTransientState<T> {
	/**
	 * Returns an object containing the plugins state.
	 * 
	 * @return Object to be return in the restoreTransientState() method.
	 */
	public T getTransientState();

	/**
	 * Provides the transient state object that was returned in the corresponding
	 * {@link #getTransientState()} call.
	 * 
	 * @param state the state object that was generated by this plugin's getTransientState() method.
	 */
	public void restoreTransientState(T state);

	/**
	 * Already required/provided by {@link Plugin}
	 * 
	 * @return true if the plugin has been disposed
	 */
	public boolean isDisposed();
}
