// This file will eventually be incorporate upstream in the CTADL project.
// It resides here purely to facilitate coordination.
#pragma once

// UTILITY VARIABLES
.decl pcode_id(id: PCodeInstruction, rep: symbol)
.decl vnode_id(id: symbol, addr: symbol)
.decl varnode_hfunc(id: symbol, hfunc_id: PCodeHighFunc)
.decl varnode_hvar(id: symbol, hvar_id: symbol)
.decl op_hfunc(id: symbol, hfunc_id: PCodeHighFunc)
.decl bb_hfunc(id: symbol, hfunc_id: PCodeHighFunc)
.decl location_hfunc(id: symbol, hfunc_id: PCodeHighFunc)
.decl tmp(key: symbol, val: symbol)

.decl HFUNC_FUNCX(id: PCodeHighFunc, f: symbol)
.decl HFUNC_NAMEX(id: PCodeHighFunc, f: symbol)
.decl HFUNC_ISEXTX(id: PCodeHighFunc)
.decl HFUNC_PROTOX(id: PCodeHighFunc, proto: PCodeHighPrototype)
.decl HFUNC_EPX(id: PCodeHighFunc, ep: symbol)
.decl HFUNC_LOCAL_EPX(id: symbol, addr: symbol)
//.decl HFUNC_ISEXTX(id: PCodeHighFunc)

.decl BB_EDGE(from: PCodeBlockBasic, to: PCodeBlockBasic)
.decl BB_FIRSTX(bbid: PCodeBlockBasic, id: PCodeInstruction)
.decl BB_HFUNCX(bbid: PCodeBlockBasic, f: PCodeHighFunc)

.decl hvar_hfunc(id: symbol, vnode_id: symbol)
.decl HVAR_NAMEX(id: symbol, name: symbol)
.decl HVAR_TYPEX(id: symbol, type: PCodeType)
.decl HVAR_REPRESENTATIVEX(id: symbol, vnode_id: symbol)

.decl PCODE_MNEMONICX(id: PCodeInstruction, mnemonic: symbol)
.decl PCODE_PARENTX(id: PCodeInstruction, bbid: PCodeBlockBasic)
.decl PCODE_TARGETX(id: PCodeInstruction, target_address: symbol)
.decl PCODE_INPUTX(id: PCodeInstruction, i: number, vnode_id: symbol)
.decl PCODE_OUTPUTX(id: PCodeInstruction, vnode_id: symbol)
.decl PCODE_OPCODEX(id: PCodeInstruction, opcode: symbol)
.decl PCODE_NEXTX(prev: PCodeInstruction, next: PCodeInstruction)
.decl PCODE_INDEXX(prev: PCodeInstruction, i: number)

.decl VNODE_ADDRESSX(id: symbol, address: symbol)
.decl VNODE_PC_ADDRESSX(id: symbol, pc_address: symbol)
.decl VNODE_OFFSETX(id: symbol, offset: symbol)
.decl VNODE_OFFSET_NX(id: symbol, offset: symbol)
.decl VNODE_SIZEX(id: symbol, size: number)
.decl VNODE_SPACEX(id: symbol, space: symbol)
.decl VNODE_HVARX(id: symbol, hvar_id: symbol)
.decl VNODE_HFUNCX(id: symbol, hfunc_id: PCodeHighFunc)
.decl VNODE_NAMEX(id: symbol, vn: symbol)

.decl OFFSET_INDEXX(offset: symbol, idx: number)

.decl PROTO_IS_CONSTRUCTORX(id: PCodeHighPrototype)
.decl PROTO_IS_DESTRUCTORX(id: PCodeHighPrototype)
.decl PROTO_IS_VARARGX(id: PCodeHighPrototype)
.decl PROTO_IS_INLINEX(id: PCodeHighPrototype)
.decl PROTO_IS_VOIDX(id: PCodeHighPrototype)
.decl PROTO_HAS_THISX(id: PCodeHighPrototype)
.decl PROTO_CALLING_CONVENTIONX(id: PCodeHighPrototype, cc: PCodeGenericCallingConvention)
.decl PROTO_RETTYPEX(id: PCodeHighPrototype, retty: symbol)
.decl PROTO_PARAMETERX(id: PCodeHighPrototype, n: number, p: PCodeHighSymbol)
.decl PROTO_PARAMETER_COUNTX(id: PCodeHighPrototype, n: number)
.decl PROTO_PARAMETER_DATATYPEX(id: PCodeHighSymbol, type: symbol)

.decl SYMBOL_HVARX(id: PCodeHighSymbol, hvar_id: PCodeHighVar)
.decl SYMBOL_HFUNCX(id: PCodeHighSymbol, hfunc_id: PCodeHighFunc)
.decl SYMBOL_NAMEX(id: PCodeHighSymbol, name: symbol)

.decl LOCATION_NUM(addr: symbol, off: symbol)
.decl LOCATION_HEX(addr: symbol, off: symbol)
.decl LOCATION_FUNC(addr: symbol, fn: PCodeHighFunc)
.decl LOCATION_UNIQ(addr: symbol, uniq: number)
.decl MNEMONICS(n: symbol, mnem: symbol)
.decl VARIABLE_FIELD(id: symbol, f: symbol)

.decl FUNC_ISEXT(id: PCodeHighFunc)
.decl FUNC_PARAMETER(id: PCodeHighFunc, n: number, p: PCodeHighSymbol)
.decl FUNC_PARAMETER_COUNT(id: PCodeHighFunc, n: number)
.decl FUNC_PARAMETER_DATATYPE(id: PCodeHighSymbol, n: number, type: symbol)

.decl A_ADDR_REF(addr: symbol, ref: number)
.decl A_ADDR_SIZE(addr: symbol, sz: number)
.decl A_ADDR_OFFSET(addr: symbol, off: symbol)
.decl A_ADDR_SPACE(addr: symbol, sp: symbol)

.decl E_AST_BLOCK(ast: symbol, bbid: PCodeBlockBasic)
.decl E_AST_VARNODES(ast: symbol, id: symbol)

.decl A_BLOCK_INDEX(id: PCodeBlockBasic, index: number)
.decl E_BLOCK_BLOCK(id: PCodeBlockBasic, bbid: PCodeBlockBasic)
.decl E_BLOCK_OP(bbid: PCodeBlockBasic, id: PCodeInstruction)
.decl E_BLOCK_RANGELIST(id: PCodeBlockBasic, list: symbol)
.decl E_BLOCK_STATEMENT(id: PCodeBlockBasic, s: symbol)
.decl E_BLOCK_VARIABLE(id: PCodeBlockBasic, v: symbol)

.decl A_BLOCKEDGE_INDEX(id: symbol, index: number)
.decl E_BLOCKEDGE_EDGE(id: symbol, edge: symbol)

.decl E_DOC_FUNCTION(id: PCodeHighFunc, f: symbol)

.decl A_EDGE_END(id: symbol, end: number)

.decl A_FIELD_XMLCONTENT(id: symbol, xml: symbol)

.decl E_FUNCTION_ADDR(id: symbol, addr: symbol)
.decl E_FUNCTION_AST(id: symbol, ast: symbol)
.decl E_FUNCTION_BLOCK(id: symbol, bbid: PCodeBlockBasic)
.decl E_FUNCTION_FUNCPROTO(id: symbol, proto: PCodeHighPrototype)
.decl E_FUNCTION_HIGHLIST(id: symbol, list: symbol)
.decl E_FUNCTION_LOCALDB(id: symbol, db: symbol)
.decl A_FUNCTION_NAME(id: symbol, name: symbol)
.decl E_FUNCTION_VARDECL(id: symbol, decl: symbol)

.decl E_FUNCPROTO_VARDECL(id: PCodeHighPrototype, decl: symbol)

.decl E_HIGH_ADDR(id: PCodeHighVar, addr: symbol)
.decl A_HIGH_CLASS(id: PCodeHighVar, cls: symbol)
.decl A_HIGH_REPREF(id: PCodeHighVar, ref: number)
.decl A_HIGH_SYMREF(id: PCodeHighVar, ref: number)
.decl E_HIGH_TYPE(id: PCodeHighVar, type: PCodeType)
.decl E_HIGH_TYPEREF(id: PCodeHighVar, type: PCodeType)
.decl E_HIGHLIST_HIGH(id: symbol, high: PCodeHighVar)

.decl A_IOP_VALUE(id: symbol, n: symbol)

.decl A_INPUT_INDEX(id: symbol, n: number)

.decl E_LOCALDB_SCOPE(db: symbol, scope: symbol)

.decl E_MAPSYM_SYMBOL(map: symbol, id: PCodeHighSymbol)

.decl E_OP_ADDR(id: PCodeInstruction, addr: symbol)
.decl A_OP_CODE(id: PCodeInstruction, mn: symbol)
.decl E_OP_IOP(id: PCodeInstruction, val: symbol)
.decl A_OP_INDEX(id: PCodeInstruction, n: number)
.decl E_OP_INPUT(id: PCodeInstruction, vn: symbol)
.decl E_OP_OUTPUT(id: PCodeInstruction, vn: symbol)
.decl A_OP_OPREF(id: PCodeInstruction, ref: number)
.decl E_OP_SEQNUM(id: PCodeInstruction, sq: symbol)
.decl E_OP_SPACEID(id: PCodeInstruction, val: symbol)

.decl A_PROTOTYPE_CONSTRUCTOR(id: PCodeHighPrototype, val: symbol)
.decl A_PROTOTYPE_DESTRUCTOR(id: PCodeHighPrototype, val: symbol)
.decl A_PROTOTYPE_DOTDOTDOT(id: PCodeHighPrototype, val: symbol)
.decl A_PROTOTYPE_INLINE(id: PCodeHighPrototype, val: symbol)   
.decl A_PROTOTYPE_MODEL(id: PCodeHighPrototype, cc: PCodeGenericCallingConvention)   
.decl E_PROTOTYPE_RETURNSYM(id: PCodeHighPrototype, ret: symbol)   

.decl E_RANGELIST_RANGE(id: symbol, rng: symbol)
.decl A_RANGE_FIRST(id: symbol, addr: symbol)
.decl A_RANGE_LAST(id: symbol, addr: symbol)

.decl E_RETURNSYM_VOID(id: symbol, void: symbol)   
.decl E_RETURNSYM_TYPE(id: symbol, type: symbol)   
.decl E_RETURNSYM_TYPEREF(id: symbol, ref: symbol)   

.decl E_SCOPE_SYMBOLLIST(scope: symbol, list: symbol)

.decl A_SEQNUM_OFFSET(sq: symbol, target_address: symbol)
.decl A_SEQNUM_OFFSET_N(addr: symbol, off: number)
.decl A_SEQNUM_OFFSET_HEX(addr: symbol, off: symbol)
.decl A_SEQNUM_OFFSET_UNIQ(off: symbol, uniq: number)
.decl A_SEQNUM_UNIQ(sq: symbol, ref: number)

.decl A_SPACEID_NAME(s: symbol, ref: symbol)

.decl E_STATEMENT_FIELD(s: symbol, fn: symbol)
.decl E_STATEMENT_FUNCNAME(s: symbol, fn: symbol)
.decl E_STATEMENT_OP(s: symbol, op: PCodeInstruction)
.decl A_STATEMENT_OPREF(s: symbol, ref: number)
.decl E_STATEMENT_VARIABLE(s: symbol, id: symbol)

.decl E_SYMBOLLIST_MAPSYM(list: symbol, map: symbol)
.decl A_SYMBOL_CAT(id: PCodeHighSymbol, category: number)
.decl A_SYMBOL_INDEX(id: PCodeHighSymbol, index: number)
.decl A_SYMBOL_NAME(id: PCodeHighSymbol, name: symbol)
.decl A_SYMBOL_ID(id: PCodeHighSymbol, ref: number)
.decl E_SYMBOL_TYPE(id: PCodeHighSymbol, type: symbol)
.decl E_SYMBOL_TYPEREF(id: PCodeHighSymbol, ref: symbol)

.decl A_TYPE_NAME(id: PCodeType, name: symbol)
.decl A_TYPE_METATYPE(id: PCodeType, meta: PCodeType)
.decl A_TYPE_SIZE(id: PCodeType, sz: number)
.decl E_TYPE_TYPEREF(id: PCodeType, ref: symbol)
.decl A_TYPEREF_NAME(id: symbol, name: symbol)

.decl E_VARDECL_VARIABLE(id: symbol, v: symbol)
.decl A_VARIABLE_OPREF(id: symbol, ref: number)
.decl A_VARIABLE_VARREF(id: symbol, ref: number)
.decl A_VARIABLE_XMLCONTENT(id: symbol, name: symbol)
.decl E_VARNODES_ADDR(id: symbol, addr: symbol)
    
