/* ###
 * IP: Apache License 2.0 with LLVM Exceptions
 */
package SWIG;


/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class RegisterKind {
  public final static RegisterKind eRegisterKindEHFrame = new RegisterKind("eRegisterKindEHFrame", lldbJNI.eRegisterKindEHFrame_get());
  public final static RegisterKind eRegisterKindDWARF = new RegisterKind("eRegisterKindDWARF");
  public final static RegisterKind eRegisterKindGeneric = new RegisterKind("eRegisterKindGeneric");
  public final static RegisterKind eRegisterKindProcessPlugin = new RegisterKind("eRegisterKindProcessPlugin");
  public final static RegisterKind eRegisterKindLLDB = new RegisterKind("eRegisterKindLLDB");
  public final static RegisterKind kNumRegisterKinds = new RegisterKind("kNumRegisterKinds");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static RegisterKind swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + RegisterKind.class + " with value " + swigValue);
  }

  private RegisterKind(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private RegisterKind(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private RegisterKind(String swigName, RegisterKind swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static RegisterKind[] swigValues = { eRegisterKindEHFrame, eRegisterKindDWARF, eRegisterKindGeneric, eRegisterKindProcessPlugin, eRegisterKindLLDB, kNumRegisterKinds };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

