/* ###
 * IP: Apache License 2.0 with LLVM Exceptions
 */
package SWIG;


/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SBAttachInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SBAttachInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SBAttachInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        lldbJNI.delete_SBAttachInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SBAttachInfo() {
    this(lldbJNI.new_SBAttachInfo__SWIG_0(), true);
  }

  public SBAttachInfo(java.math.BigInteger pid) {
    this(lldbJNI.new_SBAttachInfo__SWIG_1(pid), true);
  }

  public SBAttachInfo(String path, boolean wait_for) {
    this(lldbJNI.new_SBAttachInfo__SWIG_2(path, wait_for), true);
  }

  public SBAttachInfo(String path, boolean wait_for, boolean async) {
    this(lldbJNI.new_SBAttachInfo__SWIG_3(path, wait_for, async), true);
  }

  public SBAttachInfo(SBAttachInfo rhs) {
    this(lldbJNI.new_SBAttachInfo__SWIG_4(SBAttachInfo.getCPtr(rhs), rhs), true);
  }

  public java.math.BigInteger GetProcessID() {
    return lldbJNI.SBAttachInfo_GetProcessID(swigCPtr, this);
  }

  public void SetProcessID(java.math.BigInteger pid) {
    lldbJNI.SBAttachInfo_SetProcessID(swigCPtr, this, pid);
  }

  public void SetExecutable(String path) {
    lldbJNI.SBAttachInfo_SetExecutable__SWIG_0(swigCPtr, this, path);
  }

  public void SetExecutable(SBFileSpec exe_file) {
    lldbJNI.SBAttachInfo_SetExecutable__SWIG_1(swigCPtr, this, SBFileSpec.getCPtr(exe_file), exe_file);
  }

  public boolean GetWaitForLaunch() {
    return lldbJNI.SBAttachInfo_GetWaitForLaunch(swigCPtr, this);
  }

  public void SetWaitForLaunch(boolean b) {
    lldbJNI.SBAttachInfo_SetWaitForLaunch__SWIG_0(swigCPtr, this, b);
  }

  public void SetWaitForLaunch(boolean b, boolean async) {
    lldbJNI.SBAttachInfo_SetWaitForLaunch__SWIG_1(swigCPtr, this, b, async);
  }

  public boolean GetIgnoreExisting() {
    return lldbJNI.SBAttachInfo_GetIgnoreExisting(swigCPtr, this);
  }

  public void SetIgnoreExisting(boolean b) {
    lldbJNI.SBAttachInfo_SetIgnoreExisting(swigCPtr, this, b);
  }

  public long GetResumeCount() {
    return lldbJNI.SBAttachInfo_GetResumeCount(swigCPtr, this);
  }

  public void SetResumeCount(long c) {
    lldbJNI.SBAttachInfo_SetResumeCount(swigCPtr, this, c);
  }

  public String GetProcessPluginName() {
    return lldbJNI.SBAttachInfo_GetProcessPluginName(swigCPtr, this);
  }

  public void SetProcessPluginName(String plugin_name) {
    lldbJNI.SBAttachInfo_SetProcessPluginName(swigCPtr, this, plugin_name);
  }

  public long GetUserID() {
    return lldbJNI.SBAttachInfo_GetUserID(swigCPtr, this);
  }

  public long GetGroupID() {
    return lldbJNI.SBAttachInfo_GetGroupID(swigCPtr, this);
  }

  public boolean UserIDIsValid() {
    return lldbJNI.SBAttachInfo_UserIDIsValid(swigCPtr, this);
  }

  public boolean GroupIDIsValid() {
    return lldbJNI.SBAttachInfo_GroupIDIsValid(swigCPtr, this);
  }

  public void SetUserID(long uid) {
    lldbJNI.SBAttachInfo_SetUserID(swigCPtr, this, uid);
  }

  public void SetGroupID(long gid) {
    lldbJNI.SBAttachInfo_SetGroupID(swigCPtr, this, gid);
  }

  public long GetEffectiveUserID() {
    return lldbJNI.SBAttachInfo_GetEffectiveUserID(swigCPtr, this);
  }

  public long GetEffectiveGroupID() {
    return lldbJNI.SBAttachInfo_GetEffectiveGroupID(swigCPtr, this);
  }

  public boolean EffectiveUserIDIsValid() {
    return lldbJNI.SBAttachInfo_EffectiveUserIDIsValid(swigCPtr, this);
  }

  public boolean EffectiveGroupIDIsValid() {
    return lldbJNI.SBAttachInfo_EffectiveGroupIDIsValid(swigCPtr, this);
  }

  public void SetEffectiveUserID(long uid) {
    lldbJNI.SBAttachInfo_SetEffectiveUserID(swigCPtr, this, uid);
  }

  public void SetEffectiveGroupID(long gid) {
    lldbJNI.SBAttachInfo_SetEffectiveGroupID(swigCPtr, this, gid);
  }

  public java.math.BigInteger GetParentProcessID() {
    return lldbJNI.SBAttachInfo_GetParentProcessID(swigCPtr, this);
  }

  public void SetParentProcessID(java.math.BigInteger pid) {
    lldbJNI.SBAttachInfo_SetParentProcessID(swigCPtr, this, pid);
  }

  public boolean ParentProcessIDIsValid() {
    return lldbJNI.SBAttachInfo_ParentProcessIDIsValid(swigCPtr, this);
  }

  public SBListener GetListener() {
    return new SBListener(lldbJNI.SBAttachInfo_GetListener(swigCPtr, this), true);
  }

  public void SetListener(SBListener listener) {
    lldbJNI.SBAttachInfo_SetListener(swigCPtr, this, SBListener.getCPtr(listener), listener);
  }

}
