/* ###
 * IP: Apache License 2.0 with LLVM Exceptions
 */
package SWIG;


/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SBFileSpec {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SBFileSpec(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SBFileSpec obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        lldbJNI.delete_SBFileSpec(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SBFileSpec() {
    this(lldbJNI.new_SBFileSpec__SWIG_0(), true);
  }

  public SBFileSpec(SBFileSpec rhs) {
    this(lldbJNI.new_SBFileSpec__SWIG_1(SBFileSpec.getCPtr(rhs), rhs), true);
  }

  public SBFileSpec(String path) {
    this(lldbJNI.new_SBFileSpec__SWIG_2(path), true);
  }

  public SBFileSpec(String path, boolean resolve) {
    this(lldbJNI.new_SBFileSpec__SWIG_3(path, resolve), true);
  }

  public boolean IsValid() {
    return lldbJNI.SBFileSpec_IsValid(swigCPtr, this);
  }

  public boolean Exists() {
    return lldbJNI.SBFileSpec_Exists(swigCPtr, this);
  }

  public boolean ResolveExecutableLocation() {
    return lldbJNI.SBFileSpec_ResolveExecutableLocation(swigCPtr, this);
  }

  public String GetFilename() {
    return lldbJNI.SBFileSpec_GetFilename(swigCPtr, this);
  }

  public String GetDirectory() {
    return lldbJNI.SBFileSpec_GetDirectory(swigCPtr, this);
  }

  public void SetFilename(String filename) {
    lldbJNI.SBFileSpec_SetFilename(swigCPtr, this, filename);
  }

  public void SetDirectory(String directory) {
    lldbJNI.SBFileSpec_SetDirectory(swigCPtr, this, directory);
  }

  public long GetPath(String dst_path, long dst_len) {
    return lldbJNI.SBFileSpec_GetPath(swigCPtr, this, dst_path, dst_len);
  }

  public static int ResolvePath(String src_path, String dst_path, long dst_len) {
    return lldbJNI.SBFileSpec_ResolvePath(src_path, dst_path, dst_len);
  }

  public boolean GetDescription(SBStream description) {
    return lldbJNI.SBFileSpec_GetDescription(swigCPtr, this, SBStream.getCPtr(description), description);
  }

  public void AppendPathComponent(String file_or_directory) {
    lldbJNI.SBFileSpec_AppendPathComponent(swigCPtr, this, file_or_directory);
  }

  public String __str__() {
    return lldbJNI.SBFileSpec___str__(swigCPtr, this);
  }

}
