/* ###
 * IP: Apache License 2.0 with LLVM Exceptions
 */
package SWIG;


/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SBMemoryRegionInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SBMemoryRegionInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SBMemoryRegionInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        lldbJNI.delete_SBMemoryRegionInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SBMemoryRegionInfo() {
    this(lldbJNI.new_SBMemoryRegionInfo__SWIG_0(), true);
  }

  public SBMemoryRegionInfo(SBMemoryRegionInfo rhs) {
    this(lldbJNI.new_SBMemoryRegionInfo__SWIG_1(SBMemoryRegionInfo.getCPtr(rhs), rhs), true);
  }

  public void Clear() {
    lldbJNI.SBMemoryRegionInfo_Clear(swigCPtr, this);
  }

  public java.math.BigInteger GetRegionBase() {
    return lldbJNI.SBMemoryRegionInfo_GetRegionBase(swigCPtr, this);
  }

  public java.math.BigInteger GetRegionEnd() {
    return lldbJNI.SBMemoryRegionInfo_GetRegionEnd(swigCPtr, this);
  }

  public boolean IsReadable() {
    return lldbJNI.SBMemoryRegionInfo_IsReadable(swigCPtr, this);
  }

  public boolean IsWritable() {
    return lldbJNI.SBMemoryRegionInfo_IsWritable(swigCPtr, this);
  }

  public boolean IsExecutable() {
    return lldbJNI.SBMemoryRegionInfo_IsExecutable(swigCPtr, this);
  }

  public boolean IsMapped() {
    return lldbJNI.SBMemoryRegionInfo_IsMapped(swigCPtr, this);
  }

  public String GetName() {
    return lldbJNI.SBMemoryRegionInfo_GetName(swigCPtr, this);
  }

  public boolean GetDescription(SBStream description) {
    return lldbJNI.SBMemoryRegionInfo_GetDescription(swigCPtr, this, SBStream.getCPtr(description), description);
  }

  public String __str__() {
    return lldbJNI.SBMemoryRegionInfo___str__(swigCPtr, this);
  }

}
