/* ###
 * IP: Apache License 2.0 with LLVM Exceptions
 */
package SWIG;


/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SBTrace {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SBTrace(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SBTrace obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        lldbJNI.delete_SBTrace(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SBTrace() {
    this(lldbJNI.new_SBTrace(), true);
  }

  public long GetTraceData(SBError error, SWIGTYPE_p_void buf, long size, long offset, java.math.BigInteger thread_id) {
    return lldbJNI.SBTrace_GetTraceData(swigCPtr, this, SBError.getCPtr(error), error, SWIGTYPE_p_void.getCPtr(buf), size, offset, thread_id);
  }

  public long GetMetaData(SBError error, SWIGTYPE_p_void buf, long size, long offset, java.math.BigInteger thread_id) {
    return lldbJNI.SBTrace_GetMetaData(swigCPtr, this, SBError.getCPtr(error), error, SWIGTYPE_p_void.getCPtr(buf), size, offset, thread_id);
  }

  public void StopTrace(SBError error, java.math.BigInteger thread_id) {
    lldbJNI.SBTrace_StopTrace(swigCPtr, this, SBError.getCPtr(error), error, thread_id);
  }

  public void GetTraceConfig(SBTraceOptions options, SBError error) {
    lldbJNI.SBTrace_GetTraceConfig(swigCPtr, this, SBTraceOptions.getCPtr(options), options, SBError.getCPtr(error), error);
  }

  public java.math.BigInteger GetTraceUID() {
    return lldbJNI.SBTrace_GetTraceUID(swigCPtr, this);
  }

  public boolean IsValid() {
    return lldbJNI.SBTrace_IsValid(swigCPtr, this);
  }

}
