/* ###
 * IP: Apache License 2.0 with LLVM Exceptions
 */
package SWIG;


/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SBTypeEnumMember {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SBTypeEnumMember(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SBTypeEnumMember obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        lldbJNI.delete_SBTypeEnumMember(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SBTypeEnumMember() {
    this(lldbJNI.new_SBTypeEnumMember__SWIG_0(), true);
  }

  public SBTypeEnumMember(SBTypeEnumMember rhs) {
    this(lldbJNI.new_SBTypeEnumMember__SWIG_1(SBTypeEnumMember.getCPtr(rhs), rhs), true);
  }

  public boolean IsValid() {
    return lldbJNI.SBTypeEnumMember_IsValid(swigCPtr, this);
  }

  public long GetValueAsSigned() {
    return lldbJNI.SBTypeEnumMember_GetValueAsSigned(swigCPtr, this);
  }

  public java.math.BigInteger GetValueAsUnsigned() {
    return lldbJNI.SBTypeEnumMember_GetValueAsUnsigned(swigCPtr, this);
  }

  public String GetName() {
    return lldbJNI.SBTypeEnumMember_GetName(swigCPtr, this);
  }

  public SBType GetType() {
    return new SBType(lldbJNI.SBTypeEnumMember_GetType(swigCPtr, this), true);
  }

  public boolean GetDescription(SBStream description, DescriptionLevel description_level) {
    return lldbJNI.SBTypeEnumMember_GetDescription(swigCPtr, this, SBStream.getCPtr(description), description, description_level.swigValue());
  }

  public String __str__() {
    return lldbJNI.SBTypeEnumMember___str__(swigCPtr, this);
  }

}
