/* ###
 * IP: Apache License 2.0 with LLVM Exceptions
 */
package SWIG;


/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class SBValueList {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SBValueList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SBValueList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        lldbJNI.delete_SBValueList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SBValueList() {
    this(lldbJNI.new_SBValueList__SWIG_0(), true);
  }

  public SBValueList(SBValueList rhs) {
    this(lldbJNI.new_SBValueList__SWIG_1(SBValueList.getCPtr(rhs), rhs), true);
  }

  public boolean IsValid() {
    return lldbJNI.SBValueList_IsValid(swigCPtr, this);
  }

  public void Clear() {
    lldbJNI.SBValueList_Clear(swigCPtr, this);
  }

  public void Append(SBValue val_obj) {
    lldbJNI.SBValueList_Append__SWIG_0(swigCPtr, this, SBValue.getCPtr(val_obj), val_obj);
  }

  public void Append(SBValueList value_list) {
    lldbJNI.SBValueList_Append__SWIG_1(swigCPtr, this, SBValueList.getCPtr(value_list), value_list);
  }

  public long GetSize() {
    return lldbJNI.SBValueList_GetSize(swigCPtr, this);
  }

  public SBValue GetValueAtIndex(long idx) {
    return new SBValue(lldbJNI.SBValueList_GetValueAtIndex(swigCPtr, this, idx), true);
  }

  public SBValue FindValueObjectByUID(java.math.BigInteger uid) {
    return new SBValue(lldbJNI.SBValueList_FindValueObjectByUID(swigCPtr, this, uid), true);
  }

  public SBValue GetFirstValueByName(String name) {
    return new SBValue(lldbJNI.SBValueList_GetFirstValueByName(swigCPtr, this, name), true);
  }

  public String __str__() {
    return lldbJNI.SBValueList___str__(swigCPtr, this);
  }

}
