/* ###
 * IP: Apache License 2.0 with LLVM Exceptions
 */
package SWIG;


/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class TypeSummaryCapping {
  public final static TypeSummaryCapping eTypeSummaryCapped = new TypeSummaryCapping("eTypeSummaryCapped", lldbJNI.eTypeSummaryCapped_get());
  public final static TypeSummaryCapping eTypeSummaryUncapped = new TypeSummaryCapping("eTypeSummaryUncapped", lldbJNI.eTypeSummaryUncapped_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TypeSummaryCapping swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TypeSummaryCapping.class + " with value " + swigValue);
  }

  private TypeSummaryCapping(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TypeSummaryCapping(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TypeSummaryCapping(String swigName, TypeSummaryCapping swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TypeSummaryCapping[] swigValues = { eTypeSummaryCapped, eTypeSummaryUncapped };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

