/* ###
 * IP: Apache License 2.0 with LLVM Exceptions
 */
package SWIG;


/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class TypeClass {
  public final static TypeClass eTypeClassInvalid = new TypeClass("eTypeClassInvalid", lldbJNI.eTypeClassInvalid_get());
  public final static TypeClass eTypeClassArray = new TypeClass("eTypeClassArray", lldbJNI.eTypeClassArray_get());
  public final static TypeClass eTypeClassBlockPointer = new TypeClass("eTypeClassBlockPointer", lldbJNI.eTypeClassBlockPointer_get());
  public final static TypeClass eTypeClassBuiltin = new TypeClass("eTypeClassBuiltin", lldbJNI.eTypeClassBuiltin_get());
  public final static TypeClass eTypeClassClass = new TypeClass("eTypeClassClass", lldbJNI.eTypeClassClass_get());
  public final static TypeClass eTypeClassComplexFloat = new TypeClass("eTypeClassComplexFloat", lldbJNI.eTypeClassComplexFloat_get());
  public final static TypeClass eTypeClassComplexInteger = new TypeClass("eTypeClassComplexInteger", lldbJNI.eTypeClassComplexInteger_get());
  public final static TypeClass eTypeClassEnumeration = new TypeClass("eTypeClassEnumeration", lldbJNI.eTypeClassEnumeration_get());
  public final static TypeClass eTypeClassFunction = new TypeClass("eTypeClassFunction", lldbJNI.eTypeClassFunction_get());
  public final static TypeClass eTypeClassMemberPointer = new TypeClass("eTypeClassMemberPointer", lldbJNI.eTypeClassMemberPointer_get());
  public final static TypeClass eTypeClassObjCObject = new TypeClass("eTypeClassObjCObject", lldbJNI.eTypeClassObjCObject_get());
  public final static TypeClass eTypeClassObjCInterface = new TypeClass("eTypeClassObjCInterface", lldbJNI.eTypeClassObjCInterface_get());
  public final static TypeClass eTypeClassObjCObjectPointer = new TypeClass("eTypeClassObjCObjectPointer", lldbJNI.eTypeClassObjCObjectPointer_get());
  public final static TypeClass eTypeClassPointer = new TypeClass("eTypeClassPointer", lldbJNI.eTypeClassPointer_get());
  public final static TypeClass eTypeClassReference = new TypeClass("eTypeClassReference", lldbJNI.eTypeClassReference_get());
  public final static TypeClass eTypeClassStruct = new TypeClass("eTypeClassStruct", lldbJNI.eTypeClassStruct_get());
  public final static TypeClass eTypeClassTypedef = new TypeClass("eTypeClassTypedef", lldbJNI.eTypeClassTypedef_get());
  public final static TypeClass eTypeClassUnion = new TypeClass("eTypeClassUnion", lldbJNI.eTypeClassUnion_get());
  public final static TypeClass eTypeClassVector = new TypeClass("eTypeClassVector", lldbJNI.eTypeClassVector_get());
  public final static TypeClass eTypeClassOther = new TypeClass("eTypeClassOther", lldbJNI.eTypeClassOther_get());
  public final static TypeClass eTypeClassAny = new TypeClass("eTypeClassAny", lldbJNI.eTypeClassAny_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TypeClass swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TypeClass.class + " with value " + swigValue);
  }

  private TypeClass(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TypeClass(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TypeClass(String swigName, TypeClass swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TypeClass[] swigValues = { eTypeClassInvalid, eTypeClassArray, eTypeClassBlockPointer, eTypeClassBuiltin, eTypeClassClass, eTypeClassComplexFloat, eTypeClassComplexInteger, eTypeClassEnumeration, eTypeClassFunction, eTypeClassMemberPointer, eTypeClassObjCObject, eTypeClassObjCInterface, eTypeClassObjCObjectPointer, eTypeClassPointer, eTypeClassReference, eTypeClassStruct, eTypeClassTypedef, eTypeClassUnion, eTypeClassVector, eTypeClassOther, eTypeClassAny };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

