#!/usr/bin/env sh

OS=`uname -s`

SCRIPT_DIR=`echo $0 | sed -e 's/[^\/]*$//'`

WORKING_SCRIPT_DIR=`pwd`
SFILE=$WORKING_SCRIPT_DIR/ghidraSvr

success=1;
if [ "$OS" = "Linux" ]; then
        $SFILE uninstall
        success=$?
elif [ "$OS" = "Darwin" ]; then
        $SFILE uninstall
        success=$?
fi

cd "$SCRIPT_DIR"

if [ $success -eq 0 ]; then
        echo "Successfully uninstalled Ghidra Server."
        exit 0
else
        echo "Failed to uninstall Ghidra Server!"
        exit 1
fi

