/* ###
 * IP: Apache License 2.0 with LLVM Exceptions
 */
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package SWIG;

public class SBTypeFilter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SBTypeFilter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SBTypeFilter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(SBTypeFilter obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        lldbJNI.delete_SBTypeFilter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SBTypeFilter() {
    this(lldbJNI.new_SBTypeFilter__SWIG_0(), true);
  }

  public SBTypeFilter(long options) {
    this(lldbJNI.new_SBTypeFilter__SWIG_1(options), true);
  }

  public SBTypeFilter(SBTypeFilter rhs) {
    this(lldbJNI.new_SBTypeFilter__SWIG_2(SBTypeFilter.getCPtr(rhs), rhs), true);
  }

  public boolean IsValid() {
    return lldbJNI.SBTypeFilter_IsValid(swigCPtr, this);
  }

  public long GetNumberOfExpressionPaths() {
    return lldbJNI.SBTypeFilter_GetNumberOfExpressionPaths(swigCPtr, this);
  }

  public String GetExpressionPathAtIndex(long i) {
    return lldbJNI.SBTypeFilter_GetExpressionPathAtIndex(swigCPtr, this, i);
  }

  public boolean ReplaceExpressionPathAtIndex(long i, String item) {
    return lldbJNI.SBTypeFilter_ReplaceExpressionPathAtIndex(swigCPtr, this, i, item);
  }

  public void AppendExpressionPath(String item) {
    lldbJNI.SBTypeFilter_AppendExpressionPath(swigCPtr, this, item);
  }

  public void Clear() {
    lldbJNI.SBTypeFilter_Clear(swigCPtr, this);
  }

  public long GetOptions() {
    return lldbJNI.SBTypeFilter_GetOptions(swigCPtr, this);
  }

  public void SetOptions(long arg0) {
    lldbJNI.SBTypeFilter_SetOptions(swigCPtr, this, arg0);
  }

  public boolean GetDescription(SBStream description, DescriptionLevel description_level) {
    return lldbJNI.SBTypeFilter_GetDescription(swigCPtr, this, SBStream.getCPtr(description), description, description_level.swigValue());
  }

  public boolean IsEqualTo(SBTypeFilter rhs) {
    return lldbJNI.SBTypeFilter_IsEqualTo(swigCPtr, this, SBTypeFilter.getCPtr(rhs), rhs);
  }

  public String __repr__() {
    return lldbJNI.SBTypeFilter___repr__(swigCPtr, this);
  }

}
