/* ###
 * IP: Apache License 2.0 with LLVM Exceptions
 */
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package SWIG;

public final class TraceEvent {
  public final static TraceEvent eTraceEventDisabledSW = new TraceEvent("eTraceEventDisabledSW");
  public final static TraceEvent eTraceEventDisabledHW = new TraceEvent("eTraceEventDisabledHW");
  public final static TraceEvent eTraceEventCPUChanged = new TraceEvent("eTraceEventCPUChanged");
  public final static TraceEvent eTraceEventHWClockTick = new TraceEvent("eTraceEventHWClockTick");
  public final static TraceEvent eTraceEventSyncPoint = new TraceEvent("eTraceEventSyncPoint");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TraceEvent swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TraceEvent.class + " with value " + swigValue);
  }

  private TraceEvent(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TraceEvent(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TraceEvent(String swigName, TraceEvent swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TraceEvent[] swigValues = { eTraceEventDisabledSW, eTraceEventDisabledHW, eTraceEventCPUChanged, eTraceEventHWClockTick, eTraceEventSyncPoint };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

