/* ###
 * IP: Apache License 2.0 with LLVM Exceptions
 */
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package SWIG;

public final class TraceItemKind {
  public final static TraceItemKind eTraceItemKindError = new TraceItemKind("eTraceItemKindError", lldbJNI.eTraceItemKindError_get());
  public final static TraceItemKind eTraceItemKindEvent = new TraceItemKind("eTraceItemKindEvent");
  public final static TraceItemKind eTraceItemKindInstruction = new TraceItemKind("eTraceItemKindInstruction");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static TraceItemKind swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + TraceItemKind.class + " with value " + swigValue);
  }

  private TraceItemKind(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private TraceItemKind(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private TraceItemKind(String swigName, TraceItemKind swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static TraceItemKind[] swigValues = { eTraceItemKindError, eTraceItemKindEvent, eTraceItemKindInstruction };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

