#!/usr/bin/env bash

#----------------------------------------------------------------------
# Update Server Allow List launch
#----------------------------------------------------------------------

MAXMEM=128M

# Launch mode can be changed to one of the following: fg, debug, debug-suspend
LAUNCH_MODE=fg

# Set the debug address to listen on.
# NOTE: This variable is ignored if not launching in a debugging mode.
DEBUG_ADDRESS=127.0.0.1:13010

# Resolve symbolic link if present and get the directory this script lives in.
# NOTE: "readlink -f" is best but works on Linux only, "readlink" will only work if your PWD
# contains the link you are calling (which is the best we can do on macOS), and the "echo" is the 
# fallback, which doesn't attempt to do anything with links.
SCRIPT_FILE="$(readlink -f "$0" 2>/dev/null || readlink "$0" 2>/dev/null || echo "$0")"
SCRIPT_DIR="${SCRIPT_FILE%/*}"

# Set required VMARGS for jar builder application
APP_VMARGS="-DUpdateServerAllowList.Name=$(basename "${SCRIPT_FILE}")"

# Launch UpdateServerAllowList.
# DEBUG_ADDRESS set via environment for launch.sh
DEBUG_ADDRESS=${DEBUG_ADDRESS} "${SCRIPT_DIR}"/launch.sh "${LAUNCH_MODE}" jdk updateServerAllowList "${MAXMEM}" "${APP_VMARGS}" ghidra.app.util.headless.UpdateServerAllowList "$@"
