/* ###
 * IP: GHIDRA
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ghidra.program.util;

import ghidra.framework.model.DomainObjectChangeRecord;
import ghidra.program.model.dtarchive.DataTypeArchive;

/**
 * Event data for a DomainObjectChangeEvent generated by a DataTypeArchive.
 */
public class DtArchiveChangeRecord extends DomainObjectChangeRecord {

	private DataTypeArchive dataTypeStore;

	public DtArchiveChangeRecord(DataTypeArchive store, DtArchiveEvent eventType,
			Object oldValue,
			Object newValue) {
		super(eventType, oldValue, newValue);
		this.dataTypeStore = store;
	}

	/**
	 * Return the archive that is the subject of this change record.
	 * @return the object affected or null if not applicable
	 */
	public DataTypeArchive getDataStore() {
		return dataTypeStore;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder(super.toString());
		if (dataTypeStore != null) {
			builder.append(", archive = " + dataTypeStore.getName());
		}
		return builder.toString();
	}

}
