name: Dependency Submission

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Fetch Dependencies
        run: ./gradlew -I gradle/support/fetchDependencies.gradle -DhideDownloadProgress -DnoEclipse

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v6
        with:
          gradle-version: '9.4.0'
