name: Publish package to GitHub Packages
on:
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Restore Ghidra Dependency cache
        id: cache-ghidra
        uses: actions/cache/restore@v4
        with:
          path: ghidra/dependencies
          key: "${{ runner.os }}-ghidra-dependencies-${{ hashFiles('**/fetchDependencies.gradle') }}"

      - name: Fetch Ghidra Dependencies
        if: steps.cache-ghidra.outputs.cache-hit != 'true'
        run: |
          ./gradlew -I gradle/support/fetchDependencies.gradle init
        working-directory: ghidra

      - name: Publish package
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}